name: Update HackMD stats
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pipi-bear/hackmd-readme-stats@main
        with:
          hackmd_user: pipibear
          show_description: 'false'
